### ISSUE TITLE
[Bug] Platinum Random BST -> Follow Evolutions causes an exception

### ISSUE THREAD

**Issue by MClarke93** [upr-fvx/universal-pokemon-randomizer-fvx#20]
Loading a Platinum ROM, then setting Pokemon Base Statistics to "Random" and checking "Follow Evolutions" causes the following exception:

```
Randomizer Version: 1.1.0
Seed: 50766508057976
Settings String: 406AAMEAQSDAYYBiQEEAAEeCQARAQEUAAAUAEAEAAEAAAAAAAAAAAAyBDIBAAgJMgYFADIAAgABAAEBAAAAAAAUUG9rZW1vbiBQbGF0aW51bSAoVSm3yAAD48M4ig==
Java Version: 21.0.1, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Platinum (U)
Code: CPUE
Reported Support Level: Complete

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.dabomstew.pkrandom.gamedata.cueh.CopyUpEvolutionsHelper.apply(CopyUpEvolutionsHelper.java:177)
	at com.dabomstew.pkrandom.gamedata.cueh.CopyUpEvolutionsHelper.apply(CopyUpEvolutionsHelper.java:115)
	at com.dabomstew.pkrandom.randomizers.SpeciesBaseStatRandomizer.randomizeSpeciesStats(SpeciesBaseStatRandomizer.java:49)
	at com.dabomstew.pkrandom.GameRandomizer.randomize(GameRandomizer.java:266)
	at com.dabomstew.pkrandom.gui.RandomizerGUI.lambda$performRandomization$141(RandomizerGUI.java:1133)
	at java.base/java.lang.Thread.run(Thread.java:1583)

--ROM Diagnostics--
File name: Pokemon - Platinum Version (USA).nds
arm9: 4D104949
overlay9_16: 25EBE8C1
overlay9_5: 3E286491
overlay9_6: E6C5F31B
overlay9_73: C003DED1
overlay9_78: 091E8E97
application/zukanlist/zkn_data/zukan_enc_platinum.narc: 2F58506E
arc/encdata_ex.narc: 03FB3F28
battle/skill/sub_seq.narc: B02FF213
fielddata/encountdata/pl_enc_data.narc: 188084F5
fielddata/eventdata/zone_event.narc: D8BB2D84
fielddata/maptable/mapname.bin: 530174B6
fielddata/pokemon_trade/fld_trade.narc: B98CC1AF
fielddata/script/scr_seq.narc: 6D482515
itemtool/itemdata/pl_item_data.narc: AAE44533
msgdata/pl_msg.narc: 5666AAEC
poketool/personal/evo.narc: 6711E4B4
poketool/personal/pl_personal.narc: B16A8A01
poketool/personal/pms.narc: C457991B
poketool/personal/wotbl.narc: 977997B9
poketool/pokegra/otherpoke.narc: 7516AB13
poketool/pokegra/pl_pokegra.narc: 03BBC013
poketool/trainer/trdata.narc: 2EE9B886
poketool/trainer/trpoke.narc: 739A02EE
poketool/waza/pl_waza_tbl.narc: B2D18230
```

Note that I am using Randomizer **v1.1.1**, even though the report claims it's v1.1.0.

It only seems to error when "Random" and "Follow evolutions" are both used. Using "Shuffle" instead, or unchecking "Follow Evolution", allows it to generate with no errors.

**Comment by upr-fvx** [comment]
Thanks for the report!
You're in luck, as so far as this bug already being noticed, fixed, and [a new version with the remedy has been released](https://github.com/upr-fvx/universal-pokemon-randomizer-fvx/releases/tag/v1.1.2). 
Like, a couple of minutes ago ^^;. Saw this report just as I was uploading said release.
