### ISSUE TITLE
[Bug] Color palette changes don't work on .nds roms

### ISSUE THREAD

**Issue by MattCif31** [upr-fvx/universal-pokemon-randomizer-fvx#21]
**Describe the bug**
I tried using the UPR to randomize Heartgold. I found through testing that with heartgold, the randomizer works fine other than when I want to change the palettes of the pokemon. When I select the random option for color palette, I get an error in the error log, shown below:

-------------
java.lang.IndexOutOfBoundsException: Index 493 out of bounds for length 493
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.dabomstew.pkrandom.randomizers.Gen3to5PaletteRandomizer.getPalettePartDescriptions(Gen3to5PaletteRandomizer.java:142)
	at com.dabomstew.pkrandom.randomizers.Gen3to5PaletteRandomizer.populatePokemonPalettes(Gen3to5PaletteRandomizer.java:113)
	at com.dabomstew.pkrandom.randomizers.Gen3to5PaletteRandomizer.randomizePokemonPalettes(Gen3to5PaletteRandomizer.java:100)
	at com.dabomstew.pkrandom.GameRandomizer.randomize(GameRandomizer.java:662)
	at com.dabomstew.pkrandom.gui.RandomizerGUI.lambda$performRandomization$141(RandomizerGUI.java:1133)
	at java.base/java.lang.Thread.run(Thread.java:1623)
------------------

I then tried to do this change with other games, and found that emerald works, however heartgold, platinum, and black do not. These games all happen to be .nds roms as well they do not have the supported graphics option in the graphics tab of the UPR. I know it says the palette changing isn't guaranteed to work for every pokemon and whatnot, however I assumed this was still a bug that needed looking into.

**To Reproduce**
1. Open the UPR and open a nds rom, specific to my testing heartgold/platinum/black 
2. do not change any options outside of the color palette from unchanged -> random and save the rom
3. error will show in error log
4. If it works through other user testing, perhaps could be some issue specific to me, not sure

**Expected behavior**
Heartgold or any nds game should have some capacity of changing palettes, as listed in the graphics tab in the UPR

**Screenshots**
I sent the error snippet above, if any more information is needed feel free to reach out, through github or email Matthewcif31@gmail.com

**System (please complete the following information):**
 - Operating System: MacOs Ventura
 - Java Version: 20.0.1
 - Randomizer Version: UPR_FVX_v1.1.3

**Additional context**
Good luck please reach out if anything else is needed or if there is a problem on my end

**Comment by voliol** [comment]
This is a valid bug to report yes, caused by an oversight related to a recent change ^^;
Thank you for your report!

**Comment by MattCif31** [comment]
Thank you!
