### ISSUE TITLE
[Bug] Gen 4 erroneously marked as unofficial?

### ISSUE THREAD

**Issue by MClarke93** [upr-fvx/universal-pokemon-randomizer-fvx#6]
When loading any Generation 4 ROMs I've tried into either FVX 0.1.0 or 0.1.1, the app gives a warning saying that it's Unofficial ROM.
When using the launcher, the CLI will report an error similar to this when attempting to Randomize the ROM:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "com.dabomstew.pkrandom.romhandlers.RomHandler.hasMoveTutors()" because "this.romHandler" is null
        at com.dabomstew.pkrandom.gui.RandomizerGUI.enableOrDisableSubControls(RandomizerGUI.java:3556)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.lambda$new$17(RandomizerGUI.java:483)
        at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
        at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:619)
        at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:654)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.initialState(RandomizerGUI.java:2249)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.lambda$null$139(RandomizerGUI.java:1203)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
        at java.desktop/java.awt.Component.show(Component.java:1728)
        at java.desktop/java.awt.Component.setVisible(Component.java:1675)
        at java.desktop/java.awt.Window.setVisible(Window.java:1036)
        at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1015)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.lambda$null$138(RandomizerGUI.java:1120)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

This occurs when I try all of Diamond, Pearl, Platinum, HeartGold or SoulSilver. However all Gen 1, 2, 3, 5, 6, 7 games seem to work without any issues.

**When loading the exact same ROMs into ZX 4.6.0, they all work without issue**. It says "Support: Complete" and report no errors to the CLI when randomizing.

I've also done my best to confirm that they are all good dumps:
My HeartGold CRC32 is c180a0e9 ( which is good according to https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=4787 )
My SoulSilver CRC32 is d8ea6090 ( which is good according to https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=4788 )
My Diamond CRC32 is 84427823 ( which is good according to https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=1015 )
My Pearl CRC32 is e2d87ebf ( which is probably good according to https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=1016 )
My Platinum CRC32 is 9253921d ( which is good according to https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=3541 )

**Comment by voliol** [comment]
The Gen 4 games being marked as invalid/unofficial ROMs has been remedied. However, I am not sure about the other reported issue. What caused the ROMs to be incorrectly marked _should_ not have been sufficient to cause said error message. At the same time, though, I can't seem to reproduce it; neither before these changes nor after. Is it something you run into with all Gen 4 games? What settings are you using (when the error appears)?

**Comment by MClarke93** [comment]
I can't seem to reproduce the error on v1.0.0 myself now, even trying a few different ROMs and settings.
Probably fair to just assume it's fine for now.

**Comment by voliol** [comment]
Nice! If you come across the error again, make a new issue. I'm closing this one.
